# Konfiguracja backendu - używamy GitHub
backend:
  name: github
  repo: adamsosx/portfolio # ZASTĄP!
  branch: main # lub master, lub inna gałąź, na której pracujesz
  # Opcjonalnie, jeśli używasz GitHub Pages i własnej domeny:
  # site_domain: twojadomena.com
  # base_url: https://api.github.com # Zazwyczaj nie trzeba zmieniać
  # auth_endpoint: auth # Jeśli używasz zewnętrznego serwera do autoryzacji np. Netlify Identity / GoTrue

# Gdzie przechowywać pliki multimedialne (np. obrazy)
media_folder: "static/images" # Ścieżka w repozytorium
public_folder: "/images"     # Ścieżka publiczna na stronie

# Definicje kolekcji (typy treści)
collections:
  - name: "blog" # Nazwa techniczna kolekcji
    label: "Posty Blogowe" # Etykieta widoczna w CMS
    folder: "_posts" # Folder w repozytorium, gdzie przechowywane są pliki tej kolekcji
    create: true # Czy można tworzyć nowe elementy
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Jak generować nazwę pliku (i URL)
    fields: # Pola dla każdego elementu w kolekcji
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data Publikacji", name: "date", widget: "datetime"}
      - {label: "Miniaturka", name: "thumbnail", widget: "image", required: false}
      - {label: "Treść", name: "body", widget: "markdown"}
  # Możesz dodać więcej kolekcji, np. dla stron, produktów itp.
  # - name: "pages"
  #   label: "Strony"
  #   folder: "_pages" # lub po prostu "pages"
  #   create: true
  #   fields:
  #     - {label: "Tytuł", name: "title", widget: "string"}
  #     - {label: "Treść", name: "body", widget: "markdown"}
