backend:
  name: github
  repo: adamosx/portfolio
  branch: main
  auth_type: pkce
  app_id: 0v23lir6xzYLsnBJlaBQ

media_folder: "images" # Upewnij się, że folder "images" istnieje na głównym poziomie repozytorium

collections:
  - name: "test"
    label: "Test"
    folder: "_test" # Upewnij się, że folder "_test" istnieje na głównym poziomie repozytorium
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
