backend:
  name: github
  repo: adamsosx/decap-test  # Zmień na nazwę Twojego repozytorium testowego (np. adamsosx/sveltia-test)
  branch: main                  # Twoja główna gałąź
  auth_type: pkce               # Używa bezpośredniej autoryzacji GitHub
  app_id: Ov23lisxsANoygB2K3I2  # Twój ostatni Client ID

# Konfiguracja miejsca, gdzie będą przechowywane media
media_folder: "media"             # Folder w repozytorium, gdzie CMS zapisuje media
                                  # UPEWNIJ SIĘ, ŻE TEN FOLDER ISTNIEJE!
public_folder: "/media"           # Publiczna ścieżka URL do mediów na stronie

# Definicje kolekcji
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"              # Folder w repozytorium, gdzie przechowywane są wpisy
                                  # UPEWNIJ SIĘ, ŻE TEN FOLDER ISTNIEJE!
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
