backend:
  name: github
  repo: adamosx/portfolio # Upewnij się, że to jest poprawna nazwa użytkownika/repozytorium
  branch: main
  auth_type: pkce # Dodaj tę linię, aby używać metody PKCE
  app_id: TUTAJ_WKLEJ_SWOJ_CLIENT_ID # Zastąp Client ID skopiowanym z GitHub OAuth App

media_folder: static/images # Lub "images", zgodnie z Twoją strukturą
public_folder: /images      # Lub "/static/images"
collections:
  - name: blog
    label: Blog
    folder: _posts/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
