backend:
  name: github
  repo: adamsosx/portfolio 
  branch: main 
  site_domain: awisniewski.netlify.app

media_folder: "static/images/uploads" 
public_folder: "/images/uploads"

collections:
  - name: "test_pages"
    label: "Test Pages"
    folder: "_test_pages" # Utwórz ten folder w repozytorium
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
