backend:
  name: github
  repo: adamsosx/portfolio
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test Collection"
    folder: "_test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
