backend:
  name: git-gateway
  branch: main

site_url: https://awisniewski.netlify.app
display_url: https://awisniewski.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Treść", name: "body", widget: "markdown"}
