backend:
  name: github
  repo: adamsosx/portfolio # Upewnij się, że to jest DOKŁADNIE Twoje repo
  branch: main # Lub Twoja główna gałąź
  site_domain: awisniewski.netlify.app

media_folder: "static/images/uploads" # Ścieżka musi istnieć w repo
public_folder: "/images/uploads"

collections:
  - name: "pages" # Prosta kolekcja do testu
    label: "Strony"
    folder: "_pages" # Utwórz ten folder w repo
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Treść", name: "body", widget: "markdown"}
