backend:
  name: github
  repo: adamosx/portfolio  # Upewnij się, że nazwa użytkownika i repozytorium są poprawne
  branch: main             # Gałąź, której używasz (np. main lub master)
  auth_type: pkce          # Używa bezpośredniej autoryzacji GitHub
  app_id: 0v231idBUAG3q0053Sde # Poprawny Client ID z Twojej GitHub OAuth App

# Konfiguracja mediów
# Jeśli masz katalog "images" na głównym poziomie repozytorium:
media_folder: "images"    # Folder, gdzie CMS będzie zapisywał media w repozytorium
public_folder: "/images"  # Publiczna ścieżka do mediów na Twojej stronie

# Alternatywnie, jeśli chcesz używać "static/images":
# media_folder: "static/images"
# public_folder: "/static/images" # lub "/images" jeśli Twój build proces kopiuje static/images do /images

# Definicje kolekcji (rodzajów treści)
collections:
  - name: "blog" # Nazwa techniczna kolekcji
    label: "Blog" # Etykieta wyświetlana w CMS
    folder: "_posts/blog" # Folder w repozytorium, gdzie przechowywane są wpisy tej kolekcji
                          # Upewnij się, że ten folder istnieje (np. _posts/blog/)
    create: true # Czy można tworzyć nowe wpisy
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Format nazwy pliku dla nowych wpisów
    fields: # Pola dla każdego wpisu w tej kolekcji
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Możesz dodać więcej kolekcji tutaj, np. dla projektów portfolio:
  # - name: "projects"
  #   label: "Projects"
  #   folder: "_projects" # Upewnij się, że ten folder istnieje (np. _projects/)
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Project Title", name: "title", widget: "string"}
  #     - {label: "Description", name: "description", widget: "markdown"}
  #     - {label: "Project Image", name: "image", widget: "image"}
  #     - {label: "Completion Date", name: "date", widget: "date"}
