backend:
  name: github
  repo: adamsosx/portfolio  # Potwierdź, że to jest DOKŁADNA nazwa repozytorium
  branch: main             # Potwierdź, że to jest Twoja główna gałąź
  site_id: awisniewski.netlify.app
  
media_folder: "static/images/uploads_test" # Użyj innej nazwy folderu na test, aby uniknąć konfliktów
public_folder: "/images/uploads_test"

collections:
  - name: "test_collection"
    label: "Kolekcja Testowa"
    folder: "_test_posts"  # Utwórz ten folder w swoim repozytorium
    create: true
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
