backend:
  name: git-gateway # Kluczowe dla Netlify

# Nie dodawaj na razie repo, branch, site_domain, ani base_url, ani auth_endpoint.
# Decap CMS z backendem git-gateway powinien próbować uzyskać te informacje
# z integracji Netlify Identity / Git Gateway.

# media_folder i public_folder są wymagane, nawet jeśli puste lub testowe
media_folder: "static/images/cms_uploads" # Upewnij się, że ten folder istnieje w repo lub CMS go utworzy
public_folder: "/images/cms_uploads"

collections:
  - name: "test"
    label: "Test Collection - Minimal"
    folder: "_test_minimal" # Utwórz ten folder w repozytorium
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
